### PR TITLE
2024 Campus Visits

### PR DESCRIPTION
**Pull request by ISOMERGITHUB33**
1. New page - 2024 Campus Visits
2. Updated images for "Engineering & Tech Programme Scholarship (ETPS)", "National STEM Talent Search", and "2023 Truck Visits"

### CODE REVIEW

**Review by steRoy73 — APPROVED** [review]

**Review by steRoy73 — APPROVED** [review]

**Review by steRoy73 — APPROVED** [review]
Approved

**Review by steRoy73 — APPROVED** [review]

**Review by steRoy73 — APPROVED** [review]

**Review by steRoy73 — APPROVED** [review]
Approved

**Review by steRoy73 — APPROVED** [review]

**Review by steRoy73 — APPROVED** [review]
Approved

**Review by steRoy73 — APPROVED** [review]
Good to go

**Review by steRoy73 — APPROVED** [review]

**Review by steRoy73 — APPROVED** [review]
Approved to merge

**Review by steRoy73 — APPROVED** [review]

**Review by isomeradmin — APPROVED** [review]

**Pull request merged**
